# Generated by Django 4.0.3 on 2023-02-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_conference_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='weather',
        ),
    ]
