# Base on python:3 base image
FROM python:3

# Run Python in unbuffered mode
ENV PYTHONUNBUFFERED 1

# Set the work directory to normal /app directory
WORKDIR /app

# Copy the requirements.txt into image
COPY requirements.txt requirements.txt

# Install Python requirements from requirements.txt
RUN pip install -r requirements.txt

# Run intended Python file that you create
CMD python attendees/account_info_consumer.py
