# Use teh python:3 base image
FROM python:3

# Set an environment variable so Python prints things immediately
ENV PYTHONUNBUFFERED 1

# Set working directory to /app
WORKDIR /app

# Copy the requirements.txt so we can install from it
COPY requirements.txt requirements.txt

# Install dependencies using pip
RUN pip install -r requirements.txt

# Run Django development server
CMD ["python", "presentation_mailer/consumer.py"]
